owner: Fachschaft-Informatik-Nordakademie
repo: upptime

sites:
  - name: Outline Wiki
    url: https://wiki.nak-inf.org
  - name: Authentik SSO
    url: https://auth.nak-inf.org
  - name: Pretix Shop (FS Inf)
    url: https://shop.nak-inf.org
  - name: Pretix Shop (FS BWL)
    url: https://shop.nak-bwl.de
  - name: Overleaf
    url: https://overleaf.nak-inf.org
  - name: Firefly III (FS Inf)
    url: https://budget.nak-inf.org
  - name: Firefly III (FS BWL)
    url: https://budget.nak-bwl.de
  - name: Vaultwarden
    url: https://vault.stupanak.de
  - name: Mailcow
    url: https://mx.stupanak.de
  - name: Coolify
    url: https://coolify.nak-inf.org
  - name: NPMplus
    url: https://nginx.nak-inf.org

status-website:
  cname: status.nak-inf.org
  name: Status | Fachschaft Informatik NAK
  introTitle: "Systemstatus der Fachschaft Informatik Nordakademie"
  introMessage: "Hier findest du den aktuellen Status aller Dienste der Fachschaft Informatik an der NORDAKADEMIE."
  navbar:
    - title: Status
      href: /
    - title: Wiki
      href: https://wiki.nak-inf.org
    - title: GitHub
      href: https://github.com/Fachschaft-Informatik-Nordakademie

assignees:
  - Raindancer118

i18n:
  footer: "Systemstatus der Fachschaft Informatik Nordakademie · Powered by Upptime"
